# Generated by Django 5.2.8 on 2025-12-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('height', models.IntegerField()),
                ('mass', models.IntegerField()),
                ('hair_color', models.CharField(max_length=128)),
                ('skin_color', models.CharField(max_length=100)),
                ('eye_color', models.CharField(max_length=100)),
                ('birth_year', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('homeworld', models.CharField(max_length=100)),
                ('films', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('vehicles', models.CharField(max_length=200)),
                ('starships', models.CharField(max_length=200)),
            ],
        ),
    ]
