# Generated by Django 5.2.8 on 2025-12-01 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_startapp', '0002_starships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='starships',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='my_startapp.starships'),
        ),
    ]
